spring:
  application:
    name: job
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Rahul
    username: SQL_Login
    password: Qwerty123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      pool-name: JOBCP
      connection-timeout: 30000
      max-lifeTime: 2000000
      maximum-pool-size: 100
      idle-timeout: 30000
      minimum-idle: 5
    disable-prepared-statements-pool: false
    prepared-statements-cache-size: 250
rahul:
  queue:
    broker-url: tcp://localhost:61616
    password: admin
    userName: admin
    amqComponentName: activemq
    jmsPoolMaxConnection: 100
    jmsPoolMaxActive: 10
  external:
    queues:
      first-queue: activemq:FirstQueue
      consumer1: activemq:queue:Consumer.MASH_001.VirtualTopic.Eidiko?selector=Consumer1='true'
      consumer2: activemq:queue:Consumer.MASH_002.VirtualTopic.Eidiko?selector=Consumer2='true'
      consumer3: activemq:queue:Consumer.MASH_003.VirtualTopic.Eidiko?selector=Consumer3='true'
      consumer4: activemq:queue:Consumer.MASH_004.VirtualTopic.Eidiko?selector=Consumer4='true'
    topic:
      firstTopic: activemq:topic:VirtualTopic.Eidiko
  stored-proc-name:
    get-registration-data: dbo.GET_REGISTRATION_DATA
camel:
  component:
    kafka:
      brokers: localhost:9092