spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console		
  application:
    name: job
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Rahul
    url2: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Eidiko
    username: SQL_Login
    password: Qwerty123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    h2:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 
    hikari:
      pool-name: JOBCP
      connection-timeout: 30000
      max-lifeTime: 2000000
      maximum-pool-size: 100
      idle-timeout: 30000
      minimum-idle: 5
    disable-prepared-statements-pool: false
    prepared-statements-cache-size: 250
  mail:
    host: smtp.gmail.com
    port: 587
    username: rahul.vodala@gmail.com
    password: qlaq hisd icda dajl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#    imap:
#      host: imap.gmail.com
#      port: 993
#      username: rahul.vodala@gmail.com
#      password: qlaq hisd icda dajl
#      protocol: imaps 
rahul:
  queue:
    broker-url: tcp://localhost:61616
    password: admin
    userName: admin
    amqComponentName: activemq
    jmsPoolMaxConnection: 100
    jmsPoolMaxActive: 10
  sub:
    sub-broker-url: amqp://localhost:5672
    password: admin
    userName: admin
    subComponentName: activemqsub
    jmsPoolMaxConnection: 100
    jmsPoolMaxActive: 10
  external:
    queues:
      first-queue: activemq:FirstQueue
      consumer1: activemq:queue:Consumer.MASH_001.VirtualTopic.Eidiko?selector=Consumer1='true'
      consumer2: activemq:queue:Consumer.MASH_002.VirtualTopic.Eidiko?selector=Consumer2='true'
      consumer3: activemq:queue:Consumer.MASH_003.VirtualTopic.Eidiko?selector=Consumer3='true'
      consumer4: activemq:queue:Consumer.MASH_004.VirtualTopic.Eidiko?selector=Consumer4='true'
      sub-queue: activemqsub:FirstAmqpQueue
    topic:
      firstTopic: activemq:topic:VirtualTopic.Eidiko
  stored-proc-name:
    get-registration-data: dbo.GET_REGISTRATION_DATA
    add-employee-details: dbo.AddEmployeeDetails
    employee-details: dbo.Get_Employee_Details
  autostartup:
    enabled: false 
camel:
  component:
    kafka:
      brokers: localhost:9092